//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Speech_Typing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Speech_Typing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Convert {
            get {
                object obj = ResourceManager.GetObject("Convert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Format {
            get {
                object obj = ResourceManager.GetObject("Format", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;သမ္မတ&lt;/src&gt;
        ///    &lt;trg&gt;101P_1&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;!--
        ///&lt;short&gt;
        ///   &lt;src&gt;ကဏ္ဍ&lt;/src&gt;
        ///   &lt;trg&gt;101P_2&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကျမ&lt;/src&gt;
        ///    &lt;trg&gt;101P_3&lt;/trg&gt;
        ///&lt;/short&gt;
        /// --&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;မင်္ဂလာ&lt;/src&gt;
        ///    &lt;trg&gt;101P_4&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကိစ္စ&lt;/src&gt;
        ///    &lt;trg&gt;101P_5&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ပညာ&lt;/src&gt;
        ///    &lt;trg&gt;101P_6&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;သမီး&lt;/src&gt;
        ///    &lt;trg&gt;101P_7&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PatSint {
            get {
                return ResourceManager.GetString("PatSint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;က&lt;/src&gt;
        ///    &lt;trg&gt;1000&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///   &lt;src&gt;ခ&lt;/src&gt;
        ///   &lt;trg&gt;1001&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ဂ&lt;/src&gt;
        ///    &lt;trg&gt;1002&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ဃ&lt;/src&gt;
        ///    &lt;trg&gt;1002&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;င&lt;/src&gt;
        ///    &lt;trg&gt;1004&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///	&lt;src&gt;စ&lt;/src&gt;
        ///	&lt;trg&gt;1005&lt;/trg&gt;
        ///&lt;/short&gt;
        /// &lt;short&gt;
        ///	&lt;src&gt;ဆ&lt;/src&gt;
        ///	 &lt;trg&gt;1005&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///	&lt;src&gt;ဇ&lt;/src&gt;
        ///	&lt;trg&gt;1007&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;shor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectedAll {
            get {
                return ResourceManager.GetString("SelectedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;က&lt;/src&gt;
        ///    &lt;trg&gt;1000&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ခ&lt;/src&gt;
        ///    &lt;trg&gt;1001&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ဂ&lt;/src&gt;
        ///    &lt;trg&gt;1002&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ဃ&lt;/src&gt;
        ///    &lt;trg&gt;1003&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;င&lt;/src&gt;
        ///    &lt;trg&gt;1004&lt;/trg&gt;
        ///	&lt;/short&gt;
        ///	&lt;short&gt;
        ///	&lt;src&gt;စ&lt;/src&gt;
        ///	 &lt;trg&gt;1005&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///	&lt;src&gt;ဆ&lt;/src&gt;
        ///	 &lt;trg&gt;1006&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///	&lt;src&gt;ဇ&lt;/src&gt;
        ///	 &lt;trg&gt;10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortForm1 {
            get {
                return ResourceManager.GetString("ShortForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ါ&lt;/src&gt;
        ///    &lt;trg&gt;102B&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ာ&lt;/src&gt;
        ///    &lt;trg&gt;102C&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ိ&lt;/src&gt;
        ///    &lt;trg&gt;102D&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ီ&lt;/src&gt;
        ///    &lt;trg&gt;102E&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ု&lt;/src&gt;
        ///    &lt;trg&gt;102F&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ူ&lt;/src&gt;
        ///    &lt;trg&gt;1030&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ေ&lt;/src&gt;
        ///    &lt;trg&gt;1031&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ဲ&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortForm2 {
            get {
                return ResourceManager.GetString("ShortForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;၀&lt;/src&gt;
        ///    &lt;trg&gt;1040&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၁&lt;/src&gt;
        ///    &lt;trg&gt;1041&lt;/trg&gt;
        ///  &lt;/short&gt;
        /// &lt;short&gt;
        ///    &lt;src&gt;၂&lt;/src&gt;
        ///    &lt;trg&gt;1042&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၃&lt;/src&gt;
        ///    &lt;trg&gt;1043&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၄&lt;/src&gt;
        ///    &lt;trg&gt;1044&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၅&lt;/src&gt;
        ///    &lt;trg&gt;1045&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၆&lt;/src&gt;
        ///    &lt;trg&gt;1046&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;၇&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortForm3 {
            get {
                return ResourceManager.GetString("ShortForm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer_Data&gt;
        ///  &lt;short&gt;
        ///    &lt;src&gt;ဿ&lt;/src&gt;
        ///    &lt;trg&gt;103F&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဣ&lt;/src&gt;
        ///  &lt;trg&gt;1023&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဤ&lt;/src&gt;
        ///  &lt;trg&gt;1024&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဥ&lt;/src&gt;
        ///  &lt;trg&gt;1025&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဦ&lt;/src&gt;
        ///  &lt;trg&gt;1026&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဧ&lt;/src&gt;
        ///  &lt;trg&gt;1027&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဩ&lt;/src&gt;
        ///  &lt;trg&gt;1029&lt;/trg&gt;
        ///  &lt;/short&gt;
        ///  &lt;short&gt;
        ///  &lt;src&gt;ဪ&lt;/src&gt;
        ///  &lt;trg&gt;102A&lt;/trg&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShortForm4 {
            get {
                return ResourceManager.GetString("ShortForm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Customer-Data&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကာ&lt;/src&gt;
        ///    &lt;trg&gt;1000-1&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကာ့&lt;/src&gt;
        ///    &lt;trg&gt;1000-2&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကား&lt;/src&gt;
        ///    &lt;trg&gt;1000-3&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကိ&lt;/src&gt;
        ///    &lt;trg&gt;1000-4&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကီ&lt;/src&gt;
        ///    &lt;trg&gt;1000-5&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကီး&lt;/src&gt;
        ///    &lt;trg&gt;1000-6&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကု&lt;/src&gt;
        ///    &lt;trg&gt;1000-7&lt;/trg&gt;
        ///&lt;/short&gt;
        ///&lt;short&gt;
        ///    &lt;src&gt;ကူ&lt;/src [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Syallable1000 {
            get {
                return ResourceManager.GetString("Syallable1000", resourceCulture);
            }
        }
    }
}
